### ISSUE TITLE
Support for overrides

### ISSUE THREAD

**Issue by bigsergey** [bigsergey/filenamelint#60]
# What?

Support for overriding config for different folders

# Why?

For example in React project structure can be as follows:

```js
components
 MainDashboard.js // PascalCase for components
 Button.js // PascalCase for components
reducers
 reducer1.js // kebab-case for reducers
 reducer2.js // kebab-case for reducers
```

# How?

## `eslint` like

```js
{ 
  "format": "kebabCase", // global options
  "overrides": [
     {
       "files": [
          "components/**/*",
          "other-folder/**/*"
        ],
       "format": "pascalCase"
    }
  ]
}
```

## Rules for each folder

```js
{
  "rules": [
    {
      "files": [
          "components/**/*",
          "other-folder/**/*"
        ],
       "format": "pascalCase"
    },
    {
      "files": ["components/**/*"],
      "format": "pascalCase"
    }
  ]
}
```

Which option is better?

**Comment by erykpiast** [comment]
I'd argue for ESLint-like approach. Because it's familiar and does not have any disadvantages comparing the second proposed one.

Supporting question: how do you plan to weight overrides matching the same file? In definition order (I think ESLint does exactly that, but I'm not 100% sure)? What about the narrowness of the pattern, should it matter? (feel that rhythm!) What I mean is: should be pattern like `components/common/*` be more important than `components/**/*` when validating file `components/common/Button.jsx`?

One more question: does your globbing solution support negative pattern matching? Like `!components/internal/*`, so you can *exclude* some files in the override.

**Comment by bigsergey** [comment]
@erykpiast, thanks for your involvement!

> how do you plan to weight overrides matching the same file? In definition order (I think ESLint does exactly that, but I'm not 100% sure)?

Yes, definition order matters.

> What about the narrowness of the pattern, should it matter? (feel that rhythm!) What I mean is: should be pattern like components/common/* be more important than components/**/* when validating file components/common/Button.jsx?

```
{ 
  "format": "kebabCase", // global options
  "overrides": [
     {
       "files": [
          "components/**/*"
        ],
       "format": "pascalCase"
    },
    {
      "files": [
          // overrides pascalCase format for files that are directly in the components directory
          // format option for files in nested directories will not be overwritten
          "components/*" 
        ],
       "format": "kebabCase"
    }
  ]
}
```

> does your globbing solution support negative pattern matching? Like !components/internal/*, so you can exclude some files in the override.

Project uses `fast-glob` package so you can exclude files.
